### PR TITLE
Implement __eq__ called in unittest.assertDictEqual. Fix unit tests.

### PR DESCRIPTION
**Pull request by arm77**
Tests are calling unittest.assertDictEqual but not implementing __eq__/__ne__. Fixed failing tests.

### CODE REVIEW

**Comment by gmr** [comment]
Looks like a good addition, but I'm curious why you're nuking the test data that intentionally was setup with a different delimiter.

**Comment by arm77** [comment]
In the first and second blocks of 3f54e29, the key "foo" is causing the test to fail.

In the second and third blocks I changed the delimiter from : to - since the data before it had a delimiter - otherwise the test fails.

It looked like the previous commit to this file was a careless copy/paste job.

**Comment by gmr** [comment]
Thanks for this. I picked your new functionality and added it to the class and just pushed the next version to master.  Sorry for not merging directly.

I ended up rewriting a majority of the tests.  If you're so inclined, please take a look at the changes that just landed in master for v2.

**Comment by arm77** [comment]
Looks good. I always try to implement __eq__ so you can compare using ==

**Pull request closed without merging**
